version: '1'

services:
  api_medecin:
    container_name: api_medecin
    build: .
    ports:
      - 3001:3001
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=medecinB
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=postgresdb #the name of the service that we want to connect with
    depends_on:
      - postgresdb
  postgresdb:
    container_name: postgresdb
    ports:
      - 3001:3001
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medecinDB
    volumes:
      - db_volume="/var/lib/postgres/data"

volumes:
  - db_volume={}
